### ISSUE TITLE
Webseite mit Social Media verknüpfen

### ISSUE THREAD

**Issue by david-flores-ch** [fleeds/fleeds.ch#32]
Können wir fleeds mit solchen Icons ausstatten für die Social Media Plattformen wie z.B. hier auf OwnCloud ganz unten? https://owncloud.org/
Es wäre cool wenn die im Theme so eingebettet ist das diese Logo mit den in Wordpress verknüpften Socail Media Account sich aktivieren.

**Comment by neverything** [comment]
Können ja, aber machen nein :D die Icons sehen super hässlich aus, sowas will ich nicht!
