### ISSUE TITLE
fleeds.ch Theme Logo

### ISSUE THREAD

**Issue by david-flores-ch** [fleeds/fleeds.ch#33]
Wie können wir ein Logo bzw. Vorschaubild integriere wo dann in der Theme Übersicht sichtbar ist. Momentan ist dort ja nichts zu sehen. Ich würde es schön finden dort etwas reinstellen zu können.
Ich gestalte es auch.

**Comment by neverything** [comment]
Für das Themevorschaubild erstelle ein `screenshot.png` Datei mit den gleichen Massen wie bspw. das Vorschaubild von TwentyFifteen, dieses fügst du im Theme Root Verzeichnis also `/wp-content/themes/fleeds.ch/`ein und gibst mir Bescheid, dann kann ich es in GitHub einchecken.

**Comment by david-flores-ch** [comment]
ok ist drin ;)
