### ISSUE TITLE
Keine Bilder auf Twitter...

### ISSUE THREAD

**Issue by david-flores-ch** [fleeds/fleeds.ch#43]
Leider publiziert Jetpack unsere Blogeinträge und auch andere Veröffentlichungen ohne grosses Bild. Ich habe publizieren auf Twitter im Jetpack jetzt deaktiviert und dafür JM Twitter Cards installiert und anschliessend bei Twitter Card Validator eingetragen und das dort mir gezeigte Vorschaubild entspricht meinen Vorstellungen. Habe ich das richtig gemacht?

Quelle: http://www.tobiasgillen.de/how-to-mehr-reichweite-durch-twitter-cards/

**Comment by neverything** [comment]
Funktioniert nun, musste http://fleeds.ch/wp-admin/admin.php?page=wpseo_social#top#twitterbox aktivieren.

![screenshot 2015-02-04 17 09 23](https://cloud.githubusercontent.com/assets/368120/6043980/98a9d6e6-ac90-11e4-9d6e-a83c1a99a3b8.png)
