### ISSUE TITLE
SSL Fehlermeldung

### ISSUE THREAD

**Issue by david-flores-ch** [fleeds/fleeds.ch#52]
fleeds normal angesteuert ist tiptop.
Sobald ich mich einlogge bekomme ich aber eine Verschlüsselung Fehlermeldung das nicht alle Inhalte gut sind und ich weis auch scho an was es gut liegen könne. An den Avataren oben rechts im schwarzen Balken.

**Comment by neverything** [comment]
Du hast auch noch Mixed Content Warnungen und ich würde empfehlen WordPress
nur noch über SSL auszuliefern.

2015-12-03 22:35 GMT+01:00 David Flores <notifications@github.com>:

> fleeds normal angesteuert ist tiptop.
> Sobald ich mich einlogge bekomme ich aber eine Verschlüsselung
> Fehlermeldung das nicht alle Inhalte gut sind und ich weis auch scho an was
> es gut liegen könne. An den Avataren oben rechts im schwarzen Balken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fleeds/fleeds.ch/issues/52>.
>



-- 
*required gmbh*
Silvan Hagen
WordPress & Front-end Developer, Co-Founder
+41794122599
silvan@required.ch

**Comment by david-flores-ch** [comment]
Ok was muss ich tun?

On 04.12.2015 09:11, Silvan Hagen wrote:
> Du hast auch noch Mixed Content Warnungen und ich würde empfehlen WordPress
> nur noch über SSL auszuliefern.
> 
> 2015-12-03 22:35 GMT+01:00 David Flores <notifications@github.com>:
> 
>> fleeds normal angesteuert ist tiptop.
>> Sobald ich mich einlogge bekomme ich aber eine Verschlüsselung
>> Fehlermeldung das nicht alle Inhalte gut sind und ich weis auch scho
> an was
>> es gut liegen könne. An den Avataren oben rechts im schwarzen Balken.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fleeds/fleeds.ch/issues/52>.
>>
> 
> 
> 
> -- 
> *required gmbh*
> Silvan Hagen
> WordPress & Front-end Developer, Co-Founder
> +41794122599
> silvan@required.ch
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fleeds/fleeds.ch/issues/52#issuecomment-161905124>.
> 

-- 
David Flores
Architektur und Landschaft

Tel: +41 76 386 21 24
Web: http://fleeds.ch
E-Mail: david@fleeds.ch

Richensee 21, 6285 Hitzkirch

**Comment by david-flores-ch** [comment]
Ich habe jetzt Easy HTTPS (SSL) Redirection installiert und beide Optionen aktiviert. Im Admin habe ich die Wahrnung leider immer noch. Der Rest der Seite sieht gut aus.

**Comment by neverything** [comment]
Die Warnung im Admin liegt wie gesagt am Plugin, nimm mal wp-user-avatars

2015-12-04 9:36 GMT+01:00 David Flores <notifications@github.com>:

> Ich habe jetzt Easy HTTPS (SSL) Redirection installiert und beide Optionen
> aktiviert. Im Admin habe ich die Wahrnung leider immer noch. Der Rest der
> Seite sieht gut aus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fleeds/fleeds.ch/issues/52#issuecomment-161908682>.
>



-- 
*required gmbh*
Silvan Hagen
WordPress & Front-end Developer, Co-Founder
+41794122599
silvan@required.ch

**Comment by david-flores-ch** [comment]
Tadaaaa :) !!

läuft jjuhu Danke !!! :D



On 04.12.2015 09:43, Silvan Hagen wrote:
> Die Warnung im Admin liegt wie gesagt am Plugin, nimm mal wp-user-avatars
> 
> 2015-12-04 9:36 GMT+01:00 David Flores <notifications@github.com>:
> 
>> Ich habe jetzt Easy HTTPS (SSL) Redirection installiert und beide Optionen
>> aktiviert. Im Admin habe ich die Wahrnung leider immer noch. Der Rest der
>> Seite sieht gut aus.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fleeds/fleeds.ch/issues/52#issuecomment-161908682>.
>>
> 
> 
> 
> -- 
> *required gmbh*
> Silvan Hagen
> WordPress & Front-end Developer, Co-Founder
> +41794122599
> silvan@required.ch
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fleeds/fleeds.ch/issues/52#issuecomment-161909688>.
> 

-- 
David Flores
Architektur und Landschaft

Tel: +41 76 386 21 24
Web: http://fleeds.ch
E-Mail: david@fleeds.ch

Richensee 21, 6285 Hitzkirch

**Comment by neverything** [comment]
Sehr gut, dann schliess ich das
