### ISSUE TITLE
Snowman in Header

### ISSUE THREAD

**Issue by david-flores-ch** [fleeds/fleeds.ch#53]
Hoi Sile :)
haha ja ich brauche etwas CSS Hilfe. Ich würde gerne den Schneemann etwas nach unten nehmen, mehr in Richtung Menü. Das wär sehr lieb! :)

**Comment by neverything** [comment]
Dazu müsstest du die Grösse des home-link anpassen resp. schauen dass
dieser nicht einen Abstand zum Menü hat.

2015-12-04 20:27 GMT+01:00 David Flores <notifications@github.com>:

> Hoi Sile :)
> haha ja ich brauche etwas CSS Hilfe. Ich würde gerne den Schneemann etwas
> nach unten nehmen, mehr in Richtung Menü. Das wär sehr lieb! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fleeds/fleeds.ch/issues/53>.
>



-- 
*required gmbh*
Silvan Hagen
WordPress & Front-end Developer, Co-Founder
+41794122599
silvan@required.ch

**Comment by david-flores-ch** [comment]
Ok :) han s padding vo 0px 20px uf 1px 20px umgstellt und jetzt passt.
Bin mir aber ned klar werum das funktioniert obwohl s funktioniert :)

On 07.12.2015 11:53, Silvan Hagen wrote:
> Dazu müsstest du die Grösse des home-link anpassen resp. schauen dass
> dieser nicht einen Abstand zum Menü hat.
> 
> 2015-12-04 20:27 GMT+01:00 David Flores <notifications@github.com>:
> 
>> Hoi Sile :)
>> haha ja ich brauche etwas CSS Hilfe. Ich würde gerne den Schneemann etwas
>> nach unten nehmen, mehr in Richtung Menü. Das wär sehr lieb! :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fleeds/fleeds.ch/issues/53>.
>>
> 
> 
> 
> -- 
> *required gmbh*
> Silvan Hagen
> WordPress & Front-end Developer, Co-Founder
> +41794122599
> silvan@required.ch
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fleeds/fleeds.ch/issues/53#issuecomment-162481799>.
> 

-- 
David Flores
Architektur und Landschaft

Tel: +41 76 386 21 24
Web: http://fleeds.ch
E-Mail: david@fleeds.ch

Richensee 21, 6285 Hitzkirch
